from typing import AsyncIterator, BinaryIO, Protocol

class Storage(Protocol):
    async def save(self, key: str, source: BinaryIO, content_type: str) -> None: ...

    async def open_stream(self, key: str)-> AsyncIterator[bytes]: ...

    async def delete(self, key: str) -> None: ...

    async def exists(self, key: str) -> bool: ...
    
    def url_for(self, key: str) -> str: ...
