"""add document_chunk table

Revision ID: 1f7c9392b63e
Revises: aa46dad790ca
Create Date: 2026-07-10 11:02:24.783143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector

import sqlmodel 

# revision identifiers, used by Alembic.
revision: str = '1f7c9392b63e'
down_revision: Union[str, Sequence[str], None] = 'aa46dad790ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documentchunk',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['fileobject.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documentchunk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documentchunk_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentchunk_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentchunk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentchunk_owner_id'))
        batch_op.drop_index(batch_op.f('ix_documentchunk_file_id'))

    op.drop_table('documentchunk')
    # ### end Alembic commands ###
