"""aded fileobject metadata

Revision ID: 25348828110f
Revises: bcdee608b87e
Create Date: 2026-07-01 11:12:12.934160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel 

# revision identifiers, used by Alembic.
revision: str = '25348828110f'
down_revision: Union[str, Sequence[str], None] = 'bcdee608b87e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fileobject',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SAVED', 'INFECTED', name='filestatus'), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_fileobject_checksum'), 'fileobject', ['checksum'], unique=False)
    op.create_index(op.f('ix_fileobject_owner_id'), 'fileobject', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fileobject_owner_id'), table_name='fileobject')
    op.drop_index(op.f('ix_fileobject_checksum'), table_name='fileobject')
    op.drop_table('fileobject')
    # ### end Alembic commands ###
